// Generated by Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class ReactivationThreshold;
@class NSCoder;

SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork18ActivationSettings")
@interface ActivationSettings : NSObject <NSCoding>
@property (nonatomic, readonly, strong) ReactivationThreshold * _Nonnull reactivationThresholdGenerator;
@property (nonatomic, readonly) double reactivationThreshold;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInitFrom:(ActivationSettings * _Nonnull)initFrom;
- (ActivationSettings * _Nonnull)clone;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_temporalSummation;)
+ (NSString * _Nonnull)key_temporalSummation;
+ (void)setKey_temporalSummation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_decayRate;)
+ (NSString * _Nonnull)key_decayRate;
+ (void)setKey_decayRate:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_thresholdGenerator;)
+ (NSString * _Nonnull)key_thresholdGenerator;
+ (void)setKey_thresholdGenerator:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class Identifier;
@class Logger;
@class Network;
@class LearningSettings;

SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork16DopaminergicUnit")
@interface DopaminergicUnit : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (void)learn;
- (void)unlearn;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_publishedActivation;)
+ (NSString * _Nonnull)key_publishedActivation;
+ (void)setKey_publishedActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_newActivation;)
+ (NSString * _Nonnull)key_newActivation;
+ (void)setKey_newActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_previousActivation;)
+ (NSString * _Nonnull)key_previousActivation;
+ (void)setKey_previousActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_dopaminergicDiscrepancySignal;)
+ (NSString * _Nonnull)key_dopaminergicDiscrepancySignal;
+ (void)setKey_dopaminergicDiscrepancySignal:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@property (nonatomic, readonly) double discrepancySignal;
- (void)clearDiscrepancySignal;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
@property (nonatomic, readonly) double excitatoryExcitation;
@property (nonatomic, readonly) double inhibitoryExcitation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull excitatoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull inhibitoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticExcitatoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticInhibitoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull respondentPresynapticExcitatoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull respondentPresynapticInhibitoryActivation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork12EffectorArea")
@interface EffectorArea : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger nodeCount;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network identifier:(Identifier * _Nullable)identifier OBJC_DESIGNATED_INITIALIZER;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_effectors;)
+ (NSString * _Nonnull)key_effectors;
+ (void)setKey_effectors:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork14EffectorRegion")
@interface EffectorRegion : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger areaCount;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network identifier:(Identifier * _Nullable)identifier OBJC_DESIGNATED_INITIALIZER;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (void)createArea:(NSInteger)index;
- (EffectorArea * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_effectors;)
+ (NSString * _Nonnull)key_effectors;
+ (void)setKey_effectors:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork15HippocampalUnit")
@interface HippocampalUnit : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (void)prepareActivation;
- (void)resetActivation;
- (void)commitActivation;
- (void)learn;
- (void)unlearn;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_publishedActivation;)
+ (NSString * _Nonnull)key_publishedActivation;
+ (void)setKey_publishedActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_newActivation;)
+ (NSString * _Nonnull)key_newActivation;
+ (void)setKey_newActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_hippocampalDiscrepancySignal;)
+ (NSString * _Nonnull)key_hippocampalDiscrepancySignal;
+ (void)setKey_hippocampalDiscrepancySignal:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@property (nonatomic, readonly) double discrepancySignal;
- (void)clearDiscrepancySignal;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (BOOL)containsExcitatoryPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (BOOL)containsInhibitoryPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
@property (nonatomic, readonly) double excitatoryExcitation;
@property (nonatomic, readonly) double inhibitoryExcitation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull excitatoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull inhibitoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticExcitatoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticInhibitoryActivation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork11Hippocampus")
@interface Hippocampus : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly) NSInteger areaCount;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger nodeCount;
@property (nonatomic, readonly) double hippocampalSignal;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (void)resetActivation;
- (void)prepareActivation;
- (void)commitActivation;
- (void)learn;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork16LearningSettings")
@interface LearningSettings : NSObject <NSCoding>
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInitFrom:(LearningSettings * _Nonnull)initFrom;
- (LearningSettings * _Nonnull)clone;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_excitationGainRate;)
+ (NSString * _Nonnull)key_excitationGainRate;
+ (void)setKey_excitationGainRate:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_inhibitionGainRate;)
+ (NSString * _Nonnull)key_inhibitionGainRate;
+ (void)setKey_inhibitionGainRate:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_excitationLossRate;)
+ (NSString * _Nonnull)key_excitationLossRate;
+ (void)setKey_excitationLossRate:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_inhibitionLossRate;)
+ (NSString * _Nonnull)key_inhibitionLossRate;
+ (void)setKey_inhibitionLossRate:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_weightGainThreshold;)
+ (NSString * _Nonnull)key_weightGainThreshold;
+ (void)setKey_weightGainThreshold:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class MotorAssociationLayer;

SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork20MotorAssociationArea")
@interface MotorAssociationArea : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger layerCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (MotorAssociationLayer * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
- (MotorAssociationLayer * _Nonnull)layer:(NSInteger)index;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork21MotorAssociationLayer")
@interface MotorAssociationLayer : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger nodeCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork22MotorAssociationRegion")
@interface MotorAssociationRegion : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger areaCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (MotorAssociationArea * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
- (void)createArea:(NSInteger)index;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork22MotorAssociativeNeuron")
@interface MotorAssociativeNeuron : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (void)prepareActivation;
- (void)resetActivation;
- (void)commitActivation;
- (void)learn;
- (void)unlearn;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_publishedActivation;)
+ (NSString * _Nonnull)key_publishedActivation;
+ (void)setKey_publishedActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_newActivation;)
+ (NSString * _Nonnull)key_newActivation;
+ (void)setKey_newActivation:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (BOOL)containsExcitatoryPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (BOOL)containsInhibitoryPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
@property (nonatomic, readonly) double excitatoryExcitation;
@property (nonatomic, readonly) double inhibitoryExcitation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull excitatoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull inhibitoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticExcitatoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticInhibitoryActivation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork11MotorNeuron")
@interface MotorNeuron : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (void)prepareActivation;
- (void)resetActivation;
- (void)commitActivation;
- (void)learn;
- (void)unlearn;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_publishedActivation;)
+ (NSString * _Nonnull)key_publishedActivation;
+ (void)setKey_publishedActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_newActivation;)
+ (NSString * _Nonnull)key_newActivation;
+ (void)setKey_newActivation:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
@property (nonatomic, readonly) double excitatoryExcitation;
@property (nonatomic, readonly) double inhibitoryExcitation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull excitatoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull inhibitoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticExcitatoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticInhibitoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull respondentPresynapticExcitatoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull respondentPresynapticInhibitoryActivation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork15MotorOutputArea")
@interface MotorOutputArea : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger nodeCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork17MotorOutputRegion")
@interface MotorOutputRegion : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger areaCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (MotorOutputArea * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
- (void)createArea:(NSInteger)index;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@protocol NetworkUpdater;
@class SensorRegion;
@class SensoryInputRegion;
@class SensoryAssociationRegion;
@class VentralTegmentalArea;
@class OperantTestInput;
@class RespondentTestInput;

SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork7Network")
@interface Network : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger regionCount;
@property (nonatomic, readonly) NSInteger maxFeedbackLayerDepth;
@property (nonatomic, readonly) NSInteger maxFeedbackNodeWidth;
@property (nonatomic) BOOL isLearningEnabled;
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL isUpdating;
@property (nonatomic) BOOL isUpdaterOnline;
@property (nonatomic, readonly) BOOL hasUpdater;
@property (nonatomic, strong) id <NetworkUpdater> _Nullable updater;
@property (nonatomic, readonly) double dopaminergicSignal;
@property (nonatomic, readonly) double hippocampalSignal;
@property (nonatomic, readonly, strong) SensorRegion * _Nonnull sensorRegion;
@property (nonatomic, readonly, strong) Hippocampus * _Nonnull hippocampus;
@property (nonatomic, readonly, strong) SensoryInputRegion * _Nonnull sensoryInputRegion;
@property (nonatomic, readonly, strong) SensoryAssociationRegion * _Nonnull sensoryAssociationRegion;
@property (nonatomic, readonly, strong) VentralTegmentalArea * _Nonnull vta;
@property (nonatomic, readonly, strong) MotorAssociationRegion * _Nonnull motorAssociationRegion;
@property (nonatomic, readonly, strong) MotorOutputRegion * _Nonnull motorOutputRegion;
@property (nonatomic, readonly, strong) EffectorRegion * _Nonnull effectorRegion;
- (nonnull instancetype)initWithIdentifier:(Identifier * _Nullable)identifier logger:(Logger * _Nullable)logger OBJC_DESIGNATED_INITIALIZER;
- (void)unregisterNode:(Identifier * _Nonnull)identifier;
- (void)interTrialInterval;
- (void)update;
- (void)operantNeuronsActivate:(BOOL)autoPropogate;
- (void)operantNeuronPropogateActivation;
- (void)operantNeuronsLearn;
- (void)operantNeuronsResetActivation:(BOOL)autoPropogate;
- (void)sensorsResetActivation:(BOOL)autoPropogate;
- (void)effectorsResetActivation:(BOOL)autoPropogate;
- (BOOL)isForwardConnectionFrom:(Identifier * _Nonnull)preSynapticNeuron toPostSynapticNeuron:(Identifier * _Nonnull)toPostSynapticNeuron;
- (BOOL)isBackConnectionFrom:(Identifier * _Nonnull)postSynapticNeuron toPresynapticNeuron:(Identifier * _Nonnull)toPresynapticNeuron;
- (BOOL)isDopaminergicSignalForced;
- (void)forceDopaminergicSignal:(double)signalLevel;
- (void)unforceDopaminergicSignal;
- (BOOL)isHippocampalSignalForced;
- (void)forceHippocampalSignal:(double)signalLevel;
- (void)unforceHippocampalSignal;
- (OperantTestInput * _Nonnull)createOperantTestInputNeuron:(Identifier * _Nullable)identifier areaIndex:(NSInteger)areaIndex;
- (RespondentTestInput * _Nonnull)createRespondentTestInputNeuron:(Identifier * _Nullable)identifier areaIndex:(NSInteger)areaIndex;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_identifier;)
+ (NSString * _Nonnull)key_identifier;
+ (void)setKey_identifier:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_logger;)
+ (NSString * _Nonnull)key_logger;
+ (void)setKey_logger:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_isDopaminergicSignalForced;)
+ (NSString * _Nonnull)key_isDopaminergicSignalForced;
+ (void)setKey_isDopaminergicSignalForced:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_latchedDopaminergicSignal;)
+ (NSString * _Nonnull)key_latchedDopaminergicSignal;
+ (void)setKey_latchedDopaminergicSignal:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_isHippocampalSignalForced;)
+ (NSString * _Nonnull)key_isHippocampalSignalForced;
+ (void)setKey_isHippocampalSignalForced:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_latchedHippocampalSignal;)
+ (NSString * _Nonnull)key_latchedHippocampalSignal;
+ (void)setKey_latchedHippocampalSignal:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_sensors;)
+ (NSString * _Nonnull)key_sensors;
+ (void)setKey_sensors:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_hippocampus;)
+ (NSString * _Nonnull)key_hippocampus;
+ (void)setKey_hippocampus:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_sensoryInput;)
+ (NSString * _Nonnull)key_sensoryInput;
+ (void)setKey_sensoryInput:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_sensoryAssociation;)
+ (NSString * _Nonnull)key_sensoryAssociation;
+ (void)setKey_sensoryAssociation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_motorAssociation;)
+ (NSString * _Nonnull)key_motorAssociation;
+ (void)setKey_motorAssociation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_motorOutput;)
+ (NSString * _Nonnull)key_motorOutput;
+ (void)setKey_motorOutput:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_ventralTegmentalArea;)
+ (NSString * _Nonnull)key_ventralTegmentalArea;
+ (void)setKey_ventralTegmentalArea:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_effectors;)
+ (NSString * _Nonnull)key_effectors;
+ (void)setKey_effectors:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_namedNodes_names;)
+ (NSString * _Nonnull)key_namedNodes_names;
+ (void)setKey_namedNodes_names:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_namedNodes_nodes;)
+ (NSString * _Nonnull)key_namedNodes_nodes;
+ (void)setKey_namedNodes_nodes:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_infoForNamedNodes_names;)
+ (NSString * _Nonnull)key_infoForNamedNodes_names;
+ (void)setKey_infoForNamedNodes_names:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP27BASelectionistNeuralNetwork14NetworkUpdater_")
@protocol NetworkUpdater <NSCoding>
@property (nonatomic, weak) Network * _Nullable network;
- (void)operantNeuronsActivate;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork8NodeInfo")
@interface NodeInfo : NSObject <NSCoding, NSCopying>
@property (nonatomic, readonly, strong) Identifier * _Nonnull identifier;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull explanation;
- (nonnull instancetype)initWithIdentifier:(Identifier * _Nonnull)identifier OBJC_DESIGNATED_INITIALIZER;
- (NodeInfo * _Nonnull)clone;
@property (nonatomic, readonly) NSInteger hashValue;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone;
- (BOOL)isEqual:(id _Nullable)object;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_identifier;)
+ (NSString * _Nonnull)key_identifier;
+ (void)setKey_identifier:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_name;)
+ (NSString * _Nonnull)key_name;
+ (void)setKey_name:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_title;)
+ (NSString * _Nonnull)key_title;
+ (void)setKey_title:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_explanation;)
+ (NSString * _Nonnull)key_explanation;
+ (void)setKey_explanation:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork18OperantInputNeuron")
@interface OperantInputNeuron : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork16OperantTestInput")
@interface OperantTestInput : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork38RandomizedContinuousPropogationUpdater")
@interface RandomizedContinuousPropogationUpdater : NSObject <NetworkUpdater, NSCoding>
@property (nonatomic, weak) Network * _Nullable network;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)operantNeuronsActivate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_network;)
+ (NSString * _Nonnull)key_network;
+ (void)setKey_network:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork21ReactivationThreshold")
@interface ReactivationThreshold : NSObject <NSCoding>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL defaultIsRandom;)
+ (BOOL)defaultIsRandom;
+ (void)setDefaultIsRandom:(BOOL)value;
@property (nonatomic) BOOL isRandom;
@property (nonatomic, readonly) double nextThreshold;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInitFrom:(ReactivationThreshold * _Nonnull)initFrom;
- (void)setDefaults;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_mean;)
+ (NSString * _Nonnull)key_mean;
+ (void)setKey_mean:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_standardDeviation;)
+ (NSString * _Nonnull)key_standardDeviation;
+ (void)setKey_standardDeviation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_isRandom;)
+ (NSString * _Nonnull)key_isRandom;
+ (void)setKey_isRandom:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork21RespondentInputNeuron")
@interface RespondentInputNeuron : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork19RespondentTestInput")
@interface RespondentTestInput : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork10SensorArea")
@interface SensorArea : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger nodeCount;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network identifier:(Identifier * _Nullable)identifier OBJC_DESIGNATED_INITIALIZER;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_sensors;)
+ (NSString * _Nonnull)key_sensors;
+ (void)setKey_sensors:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork12SensorRegion")
@interface SensorRegion : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger areaCount;
@property (nonatomic, readonly, copy) NSArray<SensorArea *> * _Nonnull sensors;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network identifier:(Identifier * _Nullable)identifier OBJC_DESIGNATED_INITIALIZER;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (void)createArea:(NSInteger)index;
- (SensorArea * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_sensors;)
+ (NSString * _Nonnull)key_sensors;
+ (void)setKey_sensors:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class SensoryAssociationLayer;

SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork22SensoryAssociationArea")
@interface SensoryAssociationArea : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger layerCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (SensoryAssociationLayer * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
- (SensoryAssociationLayer * _Nonnull)layer:(NSInteger)index;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork23SensoryAssociationLayer")
@interface SensoryAssociationLayer : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger nodeCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork24SensoryAssociationRegion")
@interface SensoryAssociationRegion : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger areaCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (SensoryAssociationArea * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
- (void)createArea:(NSInteger)index;
- (void)activate:(BOOL)autoPropogate;
- (void)commitActivation;
- (void)learn;
- (void)resetActivation:(BOOL)autoPropogate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork24SensoryAssociativeNeuron")
@interface SensoryAssociativeNeuron : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (void)prepareActivation;
- (void)resetActivation;
- (void)commitActivation;
- (void)learn;
- (void)unlearn;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_publishedActivation;)
+ (NSString * _Nonnull)key_publishedActivation;
+ (void)setKey_publishedActivation:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_newActivation;)
+ (NSString * _Nonnull)key_newActivation;
+ (void)setKey_newActivation:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (BOOL)containsExcitatoryPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (BOOL)containsInhibitoryPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
@property (nonatomic, readonly) double excitatoryExcitation;
@property (nonatomic, readonly) double inhibitoryExcitation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull excitatoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull inhibitoryWeights;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticExcitatoryActivation;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull operantPresynapticInhibitoryActivation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork16SensoryInputArea")
@interface SensoryInputArea : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger nodeCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation:(BOOL)autoPropogate;
- (OperantTestInput * _Nonnull)createOperantTestInputNeuron:(Identifier * _Nullable)identifier;
- (RespondentTestInput * _Nonnull)createRespondentTestInputNeuron:(Identifier * _Nullable)identifier;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork18SensoryInputRegion")
@interface SensoryInputRegion : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger areaCount;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (void)createArea:(NSInteger)index;
- (SensoryInputArea * _Nonnull)objectAtIndexedSubscript:(NSInteger)index;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation:(BOOL)autoPropogate;
- (OperantTestInput * _Nonnull)createOperantTestInputNeuron:(Identifier * _Nullable)identifier areaIndex:(NSInteger)areaIndex;
- (RespondentTestInput * _Nonnull)createRespondentTestInputNeuron:(Identifier * _Nullable)identifier areaIndex:(NSInteger)areaIndex;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork20SimpleBinaryEffector")
@interface SimpleBinaryEffector : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, readonly) BOOL hasSourceNeuron;
@property (nonatomic, readonly) BOOL isOn;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network identifier:(Identifier * _Nullable)identifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network idString:(NSString * _Nonnull)idString;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork18SimpleBinarySensor")
@interface SimpleBinarySensor : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic) BOOL isOn;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network identifier:(Identifier * _Nullable)identifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNetwork:(Network * _Nonnull)network idString:(NSString * _Nonnull)idString;
- (BOOL)containsPresynapticConnection:(Identifier * _Nonnull)targetIdentifier;
- (void)prepareActivation;
- (void)commitActivation;
- (void)resetActivation;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC27BASelectionistNeuralNetwork20VentralTegmentalArea")
@interface VentralTegmentalArea : NSObject <NSCoding>
@property (nonatomic, readonly) BOOL isStructureLocked;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly, strong) Identifier * _Nullable identifier;
@property (nonatomic, readonly, strong) Network * _Nonnull network;
@property (nonatomic, readonly, strong) Logger * _Nonnull logger;
@property (nonatomic, strong) ActivationSettings * _Nonnull activationSettings;
@property (nonatomic, strong) LearningSettings * _Nonnull learningSettings;
@property (nonatomic, readonly) NSInteger maxLayerDepth;
@property (nonatomic, readonly) NSInteger maxNodeWidth;
@property (nonatomic, readonly) NSInteger nodeCount;
@property (nonatomic, readonly) double dopaminergicSignal;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull key_neurons;)
+ (NSString * _Nonnull)key_neurons;
+ (void)setKey_neurons:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (void)resetActivation;
- (void)prepareActivation;
- (void)commitActivation;
- (void)learn;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

#pragma clang diagnostic pop
